version: "3"

services:
  zpan:
    image: saltbo/zpan
    networks:
    - system_default
    volumes:
      - "/etc/zpan:/root"

  gofc:
    networks:
    - system_default
    image: saltbo/gofc


networks:  
  system_default:
    external: true